// Generated by CoffeeScript 1.7.1
(function() {
  var OrderedHash;

  OrderedHash = (function() {
    function OrderedHash() {
      this.m_keys = [];
      this.m_vals = {};
    }

    OrderedHash.prototype.push = function(k, v) {
      if (!this.m_vals[k]) {
        this.m_keys.push(k);
      }
      return this.m_vals[k] = v;
    };

    OrderedHash.prototype.length = function() {
      return this.m_keys.length;
    };

    OrderedHash.prototype.keys = function() {
      return this.m_keys;
    };

    OrderedHash.prototype.val = function(k) {
      return this.m_vals[k];
    };

    OrderedHash.prototype.vals = function() {
      return this.m_vals;
    };

    return OrderedHash;

  })();

}).call(this);
